CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE SEQUENCE IF NOT EXISTS contract_seq START 1;

CREATE TABLE territories (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id integer REFERENCES territories(id),
  level text NOT NULL CHECK (level IN ('country','region','city','sub_city','woreda','kebele','zone')),
  name text NOT NULL,
  UNIQUE (parent_id, name)
);
CREATE UNIQUE INDEX territories_root_name_unique ON territories (name) WHERE parent_id IS NULL;

WITH country AS (
  INSERT INTO territories (level, name) VALUES ('country','Ethiopia') RETURNING id
), region AS (
  INSERT INTO territories (parent_id, level, name) SELECT id, 'region', 'Addis Ababa' FROM country RETURNING id
), city AS (
  INSERT INTO territories (parent_id, level, name) SELECT id, 'city', 'Addis Ababa' FROM region RETURNING id
)
INSERT INTO territories (parent_id, level, name) SELECT id, 'sub_city', 'Bole' FROM city;

CREATE TABLE users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  legal_name text NOT NULL CHECK (length(trim(legal_name)) >= 2),
  phone text NOT NULL UNIQUE,
  email text UNIQUE,
  role text NOT NULL CHECK (role IN ('super_admin','compliance','finance','finance_manager','master_agent','field_agent','customer','worker','property_owner')),
  territory_id integer REFERENCES territories(id),
  password_hash text NOT NULL,
  must_change_password boolean NOT NULL DEFAULT true,
  kyc_status text NOT NULL DEFAULT 'uploaded' CHECK (kyc_status IN ('uploaded','under_review','verified','rejected')),
  active boolean NOT NULL DEFAULT false,
  mfa_enabled boolean NOT NULL DEFAULT false,
  mfa_secret text,
  whatsapp_opt_in boolean NOT NULL DEFAULT false,
  failed_logins integer NOT NULL DEFAULT 0 CHECK (failed_logins >= 0),
  locked_until timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION prevent_unverified_activation() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.active AND NEW.role NOT IN ('super_admin','compliance','finance','finance_manager')
     AND NEW.kyc_status <> 'verified' THEN
    RAISE EXCEPTION 'Account must be KYC verified before activation';
  END IF;
  RETURN NEW;
END
$$;
CREATE TRIGGER users_require_kyc_before_activation
BEFORE INSERT OR UPDATE OF active, role, kyc_status ON users
FOR EACH ROW EXECUTE FUNCTION prevent_unverified_activation();

CREATE TABLE agents (
  id uuid PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  agent_type text NOT NULL CHECK (agent_type IN ('master','field')),
  parent_id uuid REFERENCES agents(id),
  territory_id integer NOT NULL REFERENCES territories(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK ((agent_type = 'master' AND parent_id IS NULL) OR (agent_type = 'field' AND parent_id IS NOT NULL))
);

CREATE TABLE leads (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  lead_type text NOT NULL CHECK (lead_type IN ('household','business','worker','property')),
  name text NOT NULL,
  phone text NOT NULL UNIQUE,
  source_agent_id uuid NOT NULL REFERENCES agents(id),
  status text NOT NULL DEFAULT 'new' CHECK (status IN ('new','qualified','converted','lost')),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE workers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  phone text NOT NULL UNIQUE,
  national_id text UNIQUE,
  sector text NOT NULL,
  skills text[] NOT NULL DEFAULT '{}',
  languages text[] NOT NULL DEFAULT '{}',
  experience_years integer NOT NULL DEFAULT 0 CHECK (experience_years >= 0),
  rate_expected numeric(14,2) NOT NULL CHECK (rate_expected >= 0),
  availability text NOT NULL DEFAULT 'immediate' CHECK (availability IN ('immediate','within_2_weeks','later','unavailable')),
  verification text NOT NULL DEFAULT 'uploaded' CHECK (verification IN ('uploaded','under_review','verified','rejected')),
  territory_id integer NOT NULL REFERENCES territories(id),
  source_agent_id uuid NOT NULL REFERENCES agents(id),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE documents (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  worker_id uuid NOT NULL REFERENCES workers(id) ON DELETE CASCADE,
  doc_type text NOT NULL CHECK (doc_type IN ('national_id','police_clearance','reference','certificate')),
  storage_key uuid NOT NULL UNIQUE,
  sha256 text NOT NULL CHECK (sha256 ~ '^[0-9a-f]{64}$'),
  expires_on date,
  issued_on date,
  mime text NOT NULL CHECK (mime IN ('application/pdf','image/jpeg','image/png')),
  size_bytes integer NOT NULL CHECK (size_bytes BETWEEN 1 AND 10485760),
  status text NOT NULL DEFAULT 'uploaded' CHECK (status IN ('uploaded','under_review','verified','rejected','expired','superseded')),
  uploaded_by uuid NOT NULL DEFAULT nullif(current_setting('app.user_id', true), '')::uuid REFERENCES users(id),
  reviewer_id uuid REFERENCES users(id),
  reviewed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE job_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  lead_id uuid NOT NULL REFERENCES leads(id),
  sector text NOT NULL,
  skills_required text[] NOT NULL DEFAULT '{}',
  languages_required text[] NOT NULL DEFAULT '{}',
  min_experience integer NOT NULL DEFAULT 0 CHECK (min_experience >= 0),
  rate_offered numeric(14,2) NOT NULL CHECK (rate_offered > 0),
  territory_id integer NOT NULL REFERENCES territories(id),
  source_agent_id uuid NOT NULL REFERENCES agents(id),
  status text NOT NULL DEFAULT 'open' CHECK (status IN ('open','matched','closed','cancelled')),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE matches (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  request_id uuid NOT NULL REFERENCES job_requests(id),
  worker_id uuid NOT NULL REFERENCES workers(id),
  score numeric(5,1) NOT NULL CHECK (score BETWEEN 0 AND 100),
  status text NOT NULL DEFAULT 'proposed' CHECK (status IN ('proposed','accepted','declined')),
  created_by uuid NOT NULL REFERENCES users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (request_id, worker_id)
);

CREATE OR REPLACE FUNCTION check_match_worker_verified() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM workers w
    WHERE w.id = NEW.worker_id AND w.verification = 'verified'
      AND EXISTS (SELECT 1 FROM documents d WHERE d.worker_id = w.id AND d.doc_type = 'national_id' AND d.status = 'verified' AND (d.expires_on IS NULL OR d.expires_on > current_date))
      AND EXISTS (SELECT 1 FROM documents d WHERE d.worker_id = w.id AND d.doc_type = 'police_clearance' AND d.status = 'verified' AND (d.expires_on IS NULL OR d.expires_on > current_date))
  ) THEN
    RAISE EXCEPTION 'Worker is not verified';
  END IF;
  RETURN NEW;
END
$$;
CREATE TRIGGER matches_require_verified_worker BEFORE INSERT ON matches
FOR EACH ROW EXECUTE FUNCTION check_match_worker_verified();

CREATE TABLE properties (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  address text NOT NULL,
  ptype text NOT NULL CHECK (ptype IN ('apartment_building','house','commercial','land')),
  territory_id integer NOT NULL REFERENCES territories(id),
  owner_lead_id uuid REFERENCES leads(id),
  source_agent_id uuid NOT NULL REFERENCES agents(id),
  status text NOT NULL DEFAULT 'available',
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX properties_address_territory_unique ON properties (lower(address), territory_id);

CREATE TABLE property_units (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  property_id uuid NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
  unit_no text NOT NULL,
  floor integer,
  ptype text NOT NULL DEFAULT 'apartment',
  rent numeric(14,2) CHECK (rent IS NULL OR rent >= 0),
  occupancy text NOT NULL DEFAULT 'vacant' CHECK (occupancy IN ('vacant','occupied','maintenance')),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (property_id, unit_no)
);

CREATE TABLE tenants (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  phone text NOT NULL UNIQUE,
  national_id text UNIQUE,
  source_agent_id uuid NOT NULL REFERENCES agents(id),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE leases (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  unit_id uuid NOT NULL REFERENCES property_units(id),
  tenant_id uuid NOT NULL REFERENCES tenants(id),
  rent numeric(14,2) NOT NULL CHECK (rent > 0),
  deposit numeric(14,2) NOT NULL DEFAULT 0 CHECK (deposit >= 0),
  start_date date NOT NULL,
  end_date date NOT NULL CHECK (end_date >= start_date),
  source_agent_id uuid NOT NULL REFERENCES agents(id),
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','ended')),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE rent_charges (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  lease_id uuid NOT NULL REFERENCES leases(id),
  period date NOT NULL,
  due_on date NOT NULL,
  amount numeric(14,2) NOT NULL CHECK (amount > 0),
  status text NOT NULL DEFAULT 'due' CHECK (status IN ('due','paid','waived')),
  paid_at timestamptz,
  payment_ref text,
  recorded_by uuid REFERENCES users(id),
  UNIQUE (lease_id, period)
);

CREATE TABLE contracts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  contract_no text NOT NULL UNIQUE,
  lead_id uuid NOT NULL REFERENCES leads(id),
  source_agent_id uuid NOT NULL REFERENCES agents(id),
  track text NOT NULL CHECK (track IN ('A','B')),
  is_renewal boolean NOT NULL DEFAULT false,
  base_value numeric(14,2) NOT NULL CHECK (base_value > 0),
  onboarding_amt numeric(14,2) NOT NULL DEFAULT 0 CHECK (onboarding_amt >= 0),
  guarantee_amt numeric(14,2) NOT NULL DEFAULT 0 CHECK (guarantee_amt >= 0),
  monthly_mgmt_amt numeric(14,2) NOT NULL DEFAULT 0 CHECK (monthly_mgmt_amt >= 0),
  employer_fee_amt numeric(14,2) NOT NULL DEFAULT 0 CHECK (employer_fee_amt >= 0),
  other_fee_amt numeric(14,2) NOT NULL DEFAULT 0 CHECK (other_fee_amt >= 0),
  state text NOT NULL DEFAULT 'draft' CHECK (state IN ('draft','compliance_review','approval_pending','signature_pending','payment_pending','payment_received','active','completed','closed','cancelled')),
  kyc_ok boolean NOT NULL DEFAULT false,
  approved_by uuid REFERENCES users(id),
  paid_reconciled boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE invoices (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  contract_id uuid NOT NULL REFERENCES contracts(id),
  payer_name text NOT NULL,
  amount numeric(14,2) NOT NULL CHECK (amount > 0),
  due_on date NOT NULL,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','paid','void')),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE payments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  invoice_id uuid NOT NULL REFERENCES invoices(id),
  amount numeric(14,2) NOT NULL CHECK (amount > 0),
  channel text NOT NULL,
  reference text NOT NULL,
  provider_event_id text UNIQUE,
  recorded_by uuid REFERENCES users(id),
  reconciled boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (channel, reference)
);

CREATE TABLE ledger_entries (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  txn_id uuid NOT NULL,
  account text NOT NULL,
  debit numeric(14,2) NOT NULL DEFAULT 0 CHECK (debit >= 0),
  credit numeric(14,2) NOT NULL DEFAULT 0 CHECK (credit >= 0),
  ref_type text NOT NULL,
  ref_id uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK ((debit > 0 AND credit = 0) OR (credit > 0 AND debit = 0))
);
CREATE INDEX ledger_entries_ref_idx ON ledger_entries (ref_type, ref_id);

CREATE OR REPLACE FUNCTION assert_ledger_txn_balanced() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE txn uuid;
DECLARE total_debit numeric(14,2);
DECLARE total_credit numeric(14,2);
BEGIN
  txn := NEW.txn_id;
  SELECT coalesce(sum(debit),0), coalesce(sum(credit),0)
    INTO total_debit, total_credit
    FROM ledger_entries WHERE txn_id = txn;
  IF total_debit <> total_credit THEN
    RAISE EXCEPTION 'Ledger transaction % is unbalanced: debit %, credit %', txn, total_debit, total_credit;
  END IF;
  RETURN NULL;
END
$$;
CREATE CONSTRAINT TRIGGER ledger_txn_balanced
AFTER INSERT ON ledger_entries
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION assert_ledger_txn_balanced();

CREATE TABLE commission_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  agent_id uuid NOT NULL REFERENCES agents(id),
  lead_id uuid NOT NULL REFERENCES leads(id),
  contract_id uuid NOT NULL REFERENCES contracts(id),
  rule text NOT NULL DEFAULT 'first_contract',
  rate_pct numeric(7,3) NOT NULL CHECK (rate_pct >= 0),
  eligible_revenue numeric(14,2) NOT NULL CHECK (eligible_revenue >= 0),
  amount numeric(14,2) NOT NULL CHECK (amount >= 0),
  status text NOT NULL DEFAULT 'qualified' CHECK (status IN ('qualified','approved','paid','reversed')),
  qualified_by uuid REFERENCES users(id),
  approved_by uuid REFERENCES users(id),
  paid_ref text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX commission_first_contract_unique ON commission_events (lead_id, rule) WHERE rule = 'first_contract' AND status <> 'reversed';

CREATE TABLE disputes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  contract_id uuid NOT NULL REFERENCES contracts(id),
  category text NOT NULL,
  description text NOT NULL,
  opened_by uuid NOT NULL REFERENCES users(id),
  assigned_to uuid REFERENCES users(id),
  status text NOT NULL DEFAULT 'open' CHECK (status IN ('open','investigating','resolved')),
  resolution text,
  refund_amount numeric(14,2) NOT NULL DEFAULT 0 CHECK (refund_amount >= 0),
  refund_kind text CHECK (refund_kind IS NULL OR refund_kind IN ('fee','guarantee')),
  resolved_by uuid REFERENCES users(id),
  opened_at timestamptz NOT NULL DEFAULT now(),
  closed_at timestamptz
);

CREATE TABLE maintenance_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  property_id uuid NOT NULL REFERENCES properties(id),
  unit_id uuid REFERENCES property_units(id),
  description text NOT NULL,
  priority text NOT NULL DEFAULT 'normal' CHECK (priority IN ('low','normal','urgent')),
  status text NOT NULL DEFAULT 'open' CHECK (status IN ('open','assigned','in_progress','done','cancelled')),
  assigned_to text,
  cost numeric(14,2) CHECK (cost IS NULL OR cost >= 0),
  source_agent_id uuid NOT NULL REFERENCES agents(id),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE notifications (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES users(id),
  channel text NOT NULL CHECK (channel IN ('inapp','webhook')),
  template text NOT NULL,
  payload jsonb NOT NULL DEFAULT '{}',
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','sending','sent','read')),
  created_at timestamptz NOT NULL DEFAULT now(),
  sent_at timestamptz
);
CREATE INDEX notifications_queue_idx ON notifications (channel, status, id);

CREATE TABLE audit_logs (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  actor_id uuid NOT NULL REFERENCES users(id),
  action text NOT NULL,
  entity text NOT NULL,
  entity_id text NOT NULL,
  old_value jsonb,
  new_value jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE config_rules (
  key text PRIMARY KEY,
  value numeric NOT NULL
);
INSERT INTO config_rules (key, value) VALUES
  ('A_onboarding_pct',20), ('A_guarantee_pct',2), ('A_monthly_pct',5),
  ('B_employer_pct',10), ('B_other_pct',10), ('first_contract_commission_pct',50),
  ('guarantee_commissionable',0),
  ('match_w_skills',30), ('match_w_location',20), ('match_w_availability',15),
  ('match_w_experience',10), ('match_w_rate',10), ('match_w_language',10)
ON CONFLICT (key) DO NOTHING;

CREATE OR REPLACE FUNCTION app_user_id() RETURNS uuid
LANGUAGE sql STABLE AS $$
  SELECT nullif(current_setting('app.user_id', true), '')::uuid
$$;
CREATE OR REPLACE FUNCTION app_role() RETURNS text
LANGUAGE sql STABLE AS $$
  SELECT coalesce(nullif(current_setting('app.role', true), ''), '')
$$;
CREATE OR REPLACE FUNCTION app_service() RETURNS text
LANGUAGE sql STABLE AS $$
  SELECT coalesce(nullif(current_setting('app.service', true), ''), '')
$$;
CREATE OR REPLACE FUNCTION app_is_staff() RETURNS boolean
LANGUAGE sql STABLE AS $$
  SELECT app_role() IN ('super_admin','compliance','finance','finance_manager')
$$;
CREATE OR REPLACE FUNCTION app_can_access_agent(target uuid) RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
  SELECT target = app_user_id()
     OR app_is_staff()
     OR EXISTS (SELECT 1 FROM agents a WHERE a.id = target AND a.parent_id = app_user_id())
$$;

ALTER TABLE agents ENABLE ROW LEVEL SECURITY;
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE workers ENABLE ROW LEVEL SECURITY;
ALTER TABLE documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE job_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE properties ENABLE ROW LEVEL SECURITY;
ALTER TABLE property_units ENABLE ROW LEVEL SECURITY;
ALTER TABLE tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE leases ENABLE ROW LEVEL SECURITY;
ALTER TABLE rent_charges ENABLE ROW LEVEL SECURITY;
ALTER TABLE contracts ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE commission_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE disputes ENABLE ROW LEVEL SECURITY;
ALTER TABLE maintenance_requests ENABLE ROW LEVEL SECURITY;

CREATE POLICY agents_scope ON agents USING (app_can_access_agent(id)) WITH CHECK (app_role() = 'super_admin' OR app_can_access_agent(id));
CREATE POLICY leads_scope ON leads USING (app_can_access_agent(source_agent_id)) WITH CHECK (app_role() = 'super_admin' OR source_agent_id = app_user_id());
CREATE POLICY workers_scope ON workers USING (app_can_access_agent(source_agent_id)) WITH CHECK (app_role() = 'super_admin' OR source_agent_id = app_user_id());
CREATE POLICY documents_scope ON documents
  USING (app_is_staff() OR EXISTS (SELECT 1 FROM workers w WHERE w.id = worker_id AND app_can_access_agent(w.source_agent_id)))
  WITH CHECK (app_is_staff() OR EXISTS (SELECT 1 FROM workers w WHERE w.id = worker_id AND app_can_access_agent(w.source_agent_id)));
CREATE POLICY requests_scope ON job_requests USING (app_can_access_agent(source_agent_id)) WITH CHECK (app_role() = 'super_admin' OR source_agent_id = app_user_id());
CREATE POLICY matches_scope ON matches
  USING (app_is_staff() OR EXISTS (SELECT 1 FROM job_requests r WHERE r.id = request_id AND app_can_access_agent(r.source_agent_id)))
  WITH CHECK (app_is_staff());
CREATE POLICY properties_scope ON properties USING (app_can_access_agent(source_agent_id)) WITH CHECK (app_role() = 'super_admin' OR source_agent_id = app_user_id());
CREATE POLICY units_scope ON property_units
  USING (app_is_staff() OR EXISTS (SELECT 1 FROM properties p WHERE p.id = property_id AND app_can_access_agent(p.source_agent_id)))
  WITH CHECK (app_is_staff() OR EXISTS (SELECT 1 FROM properties p WHERE p.id = property_id AND app_can_access_agent(p.source_agent_id)));
CREATE POLICY tenants_scope ON tenants USING (app_can_access_agent(source_agent_id)) WITH CHECK (app_role() = 'super_admin' OR source_agent_id = app_user_id());
CREATE POLICY leases_scope ON leases USING (app_can_access_agent(source_agent_id)) WITH CHECK (app_role() = 'super_admin' OR source_agent_id = app_user_id());
CREATE POLICY charges_scope ON rent_charges
  USING (app_is_staff() OR EXISTS (SELECT 1 FROM leases l WHERE l.id = lease_id AND app_can_access_agent(l.source_agent_id)))
  WITH CHECK (app_is_staff() OR EXISTS (SELECT 1 FROM leases l WHERE l.id = lease_id AND app_can_access_agent(l.source_agent_id)));
CREATE POLICY contracts_scope ON contracts USING (app_can_access_agent(source_agent_id)) WITH CHECK (app_role() = 'super_admin' OR source_agent_id = app_user_id());
CREATE POLICY invoices_scope ON invoices USING (app_is_staff() OR app_service() = 'payment_webhook') WITH CHECK (app_is_staff() OR app_service() = 'payment_webhook');
CREATE POLICY payments_scope ON payments USING (app_is_staff() OR app_service() = 'payment_webhook') WITH CHECK (app_is_staff() OR app_service() = 'payment_webhook');
CREATE POLICY commissions_scope ON commission_events USING (app_can_access_agent(agent_id)) WITH CHECK (app_is_staff());
CREATE POLICY disputes_scope ON disputes
  USING (app_is_staff() OR EXISTS (SELECT 1 FROM contracts k WHERE k.id = contract_id AND app_can_access_agent(k.source_agent_id)))
  WITH CHECK (app_is_staff() OR opened_by = app_user_id());
CREATE POLICY maintenance_scope ON maintenance_requests USING (app_can_access_agent(source_agent_id)) WITH CHECK (app_role() = 'super_admin' OR source_agent_id = app_user_id());
